### ISSUE TITLE
Not working with Amazon Smile

### ISSUE THREAD

**Issue by nelsnich** [stephanie-wang/kindlebox#1]
While trying to register the Kindle device on smile.amazon.com, a Javascript error is thrown when clicking on the "Activate Kindlebox" button.

XMLHttpRequest cannot load https://www.amazon.com/mn/dcw/myx/ajax-activity. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://smile.amazon.com' is therefore not allowed access.

**Comment by stephanie-wang** [comment]
I think this is probably because Flask-WTF (very rightly) prevents cross origin requests. The live server has a patch that allows 'www.amazon.com' hostnames, but I'll have to do a bit more to allow all subdomains (and other countries as well). I'll notify you when smile.amazon.com becomes available on the server. For now, it's possible you can just remove the smile subdomain and still activate your account. Thanks!

**Comment by stephanie-wang** [comment]
Hey @nelsnich, I've just updated the kindlebox.me and tested it myself. Can you try registering again and confirm that it's working? Thanks!

**Comment by nelsnich** [comment]
Working great for me! Thanks! Appreciate you fixing that so fast. It wasn't a huge deal. As you said, you could take the smile off. But I have the SmileAways extension on Chrome, so it is nice to not have to disable that in order to set it up. Great work!

**Comment by stephanie-wang** [comment]
Sweet, thanks for testing that for me!

Fixed with 45f18cb.
