### ISSUE TITLE
Failed on setting up for non-US kindle account

### ISSUE THREAD

**Issue by shouya** [stephanie-wang/kindlebox#6]
Hi,

I recently failed on setting up bookdrop with my amazon.cn account. At the bookmarklet set it has successfully added the sender email to the whitelist but it showed a notification for failure. Ignoring the failure and putting files into directory didn't really work as well.

It seems bookdrop so far only support the US kindles as I searched through the code and find that `amazon.com` was written in plain here:

https://github.com/stephanie-wang/kindlebox/blob/master/app/kindleboxer.py#L513

Is there any plans for supporting kindles from zones other than US? Thank you.

**Comment by stephanie-wang** [comment]
Hi,

Sorry for the late reply! I was validating all usernames to make sure they ended with kindle.com. Some users in China weren't able to finish activating their accounts because their usernames ended with kindle.cn. Users accessing Amazon through other countries shouldn't have been affected by this.

The issue should be fixed in 085566fa4a88bee82150e844942c3677562608b7. To fix on the live site, make sure to add a new copy of the bookmarklet before trying activation again. Thanks!

Stephanie
