### ISSUE TITLE
the bookdrop_welcome.pdf haven't add to my dropbox folder which named book-drop

### ISSUE THREAD

**Issue by PokimLee** [stephanie-wang/kindlebox#8]
after aconfiguration completed, the file bookdrop_welcome.pdf didn't appear.
and I tried to put some e-book into the book-drop folder,but the e-book can't be found in my kindle.

**Comment by asgerhallas** [comment]
Same issue here :'(

**Comment by puneetar** [comment]
it is not working

**Comment by lonroth** [comment]
Do you only have the problem of the "bookdrop_welcome.pdf" not appearing or do you have the same problem as me where nothing gets transferred to the Kindle even though you drop your own files in the folder?

**Comment by puneetar** [comment]
Actually both. I don't see that file in my dropbox && also none of my files
get shared.

Thanks

**Comment by hajdbo** [comment]
same here

**Comment by stephanie-wang** [comment]
Sorry about the problems! There have been delays on the Bookdrop service due to too many users, but I'm working on a solution that I'm hoping to roll out in the next couple weeks. For now, stick with formats that don't require conversion (PDFs and .mobi files should be fine), as these are less likely to experience delays.

If you're still not receiving even the welcome file, feel free to PM me and we can try to take care of your individual case.

Thanks for your patience, everyone!
